config/routes.rb
Rails.application.routes.draw do

  # Static
  root 'static#home'
  get '/about',   to: 'static#about'

  # Users
  get '/signup',  to: 'users#signup'
  post '/signup', to: 'users#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def signup
    @sp = "hi"
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'partials/head' %>
  <body>
    <%= render 'partials/header' %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_head.html.erb
<head>
  <title>Rubynorm</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/partials/_header.html.erb
<header>
  <%= link_to "RubyNorm", root_path, id: "logo" %>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</header>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/signup.html.erb
<h1>Users#signup</h1>
<p>Find me in app/views/users/signup.html.erb</p>
<%= @sp %>